<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BillingServiceSeeder extends Seeder
{
    public function run()
    {
        DB::table('billing_services')->insert([
            [
                'id' => 1,
                'service_name' => 'Diagnosis Card',
                'description' => 'A recurring fee for hospital services that is charged after a specified number of visits. The fee is applied when the patient visits the hospital multiple times within a certain period.',
                'price' => 50.00,
                'billing_type' => 'recurring',
                'billing_interval_days' => 10,
                'is_active' => true,
                'payment_timing' => 'prepaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 1,
            ],
            [
                'id' => 2,
                'service_name' => 'Doctor Consultation',
                'description' => 'General consultation with a physician.',
                'price' => 300.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'prepaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 4,
            ],
            [
                'id' => 3,
                'service_name' => 'Emergency Care',
                'description' => 'Urgent care service for emergency cases.',
                'price' => 800.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'prepaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 5,
            ],
            [
                'id' => 4,
                'service_name' => 'Injection Service',
                'description' => 'Administration of prescribed injections.',
                'price' => 100.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'prepaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 9,
            ],
            [
                'id' => 5,
                'service_name' => 'Dressing & Wound Care',
                'description' => 'Medical dressing and wound management.',
                'price' => 250.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'prepaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 12,
            ],
            [
                'id' => 6,
                'service_name' => 'Anesthesia -spinal',
                'description' => 'Spinal anesthesia services',
                'price' => 4000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 7,
                'service_name' => 'Anesthesia -General',
                'description' => 'General anesthesia services',
                'price' => 5000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 8,
                'service_name' => 'Anesthesia',
                'description' => 'Standard anesthesia services',
                'price' => 3000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 9,
                'service_name' => 'Scrub Nurse',
                'description' => 'Scrub nurse services',
                'price' => 3000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 10,
                'service_name' => 'Nurse care per day',
                'description' => 'Full day nursing care services',
                'price' => 1000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 11,
                'service_name' => 'Nurse care half day',
                'description' => 'Half day nursing care services',
                'price' => 500.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 12,
                'service_name' => 'Midwife care per day',
                'description' => 'Full day midwife care services',
                'price' => 1000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 13,
                'service_name' => 'Midwife care half day',
                'description' => 'Half day midwife care services',
                'price' => 500.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 14,
                'service_name' => 'Doctor care per day',
                'description' => 'Full day doctor care services',
                'price' => 3000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 15,
                'service_name' => 'Doctor care half day',
                'description' => 'Half day doctor care services',
                'price' => 2000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 16,
                'service_name' => 'SVD Normal Delivery (144)',
                'description' => 'Normal spontaneous vaginal delivery',
                'price' => 10000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 17,
                'service_name' => 'SVD 1st Degree Tear (1202)',
                'description' => 'Vaginal delivery with 1st degree tear management',
                'price' => 10500.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 18,
                'service_name' => 'SVD 2nd Degree Tear (146)',
                'description' => 'Vaginal delivery with 2nd degree tear management',
                'price' => 10700.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 19,
                'service_name' => 'SVD Episiotomy + Augmentation (147)',
                'description' => 'Vaginal delivery with episiotomy and augmentation',
                'price' => 11500.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 20,
                'service_name' => 'SVD Augmentation + Tear (11000)',
                'description' => 'Vaginal delivery with augmentation and tear management',
                'price' => 11000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 21,
                'service_name' => 'Laceration (148)',
                'description' => 'Laceration repair services',
                'price' => 4700.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 22,
                'service_name' => 'SVD Instrumental Vacuum (149)',
                'description' => 'Vaginal delivery with vacuum assistance',
                'price' => 14000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 23,
                'service_name' => 'SVD Instrumental Forceps (150)',
                'description' => 'Vaginal delivery with forceps assistance',
                'price' => 15000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 24,
                'service_name' => 'SVD - Breech (151)',
                'description' => 'Breech vaginal delivery',
                'price' => 12000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 25,
                'service_name' => 'SVD Induction + tear (152)',
                'description' => 'Induced vaginal delivery with tear management',
                'price' => 12000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 26,
                'service_name' => 'SVD Augmentation (153)',
                'description' => 'Augmented vaginal delivery',
                'price' => 12000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 27,
                'service_name' => 'SVD - Normal Twins (154)',
                'description' => 'Vaginal delivery of twins',
                'price' => 18000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 28,
                'service_name' => 'SVD- 2nd Trimester Delivery (155)',
                'description' => 'Second trimester vaginal delivery',
                'price' => 7000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 29,
                'service_name' => 'SVD- PPH Management (156)',
                'description' => 'Postpartum hemorrhage management',
                'price' => 11000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 30,
                'service_name' => 'SVD- Cervical Tear Repair (157)',
                'description' => 'Cervical tear repair services',
                'price' => 13000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 31,
                'service_name' => 'SVD- EP + Augmentation (1198)',
                'description' => 'Vaginal delivery with episiotomy and augmentation',
                'price' => 5200.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 32,
                'service_name' => 'SVD-EP+Induction (1244)',
                'description' => 'Vaginal delivery with episiotomy and induction',
                'price' => 6000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 33,
                'service_name' => 'Cesarean - Primary (158)',
                'description' => 'Primary cesarean section',
                'price' => 8000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 34,
                'service_name' => 'Cesarean - 1st Scar (159)',
                'description' => 'Cesarean section with one previous scar',
                'price' => 10000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 35,
                'service_name' => 'Cesarean - 2nd Scar (1165)',
                'description' => 'Cesarean section with two previous scars',
                'price' => 11000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 36,
                'service_name' => 'Cesarean - 3rd Scar (1200)',
                'description' => 'Cesarean section with three previous scars',
                'price' => 12000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 37,
                'service_name' => 'Cesarean - 4th Scar (1201)',
                'description' => 'Cesarean section with four previous scars',
                'price' => 13000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 38,
                'service_name' => 'Cesarean - 5th Scar (1293)',
                'description' => 'Cesarean section with five previous scars',
                'price' => 14000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 39,
                'service_name' => 'Cesarean - 6th Scar (1293)',
                'description' => 'Cesarean section with six previous scars',
                'price' => 15000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 40,
                'service_name' => 'Cesarean - Twins Primary (162)',
                'description' => 'Primary cesarean section for twins',
                'price' => 8000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 41,
                'service_name' => 'Cesarean - Twins 1st Scar (163)',
                'description' => 'Cesarean section for twins with one previous scar',
                'price' => 11000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 42,
                'service_name' => 'Cesarean - Twins 2nd Scar (164)',
                'description' => 'Cesarean section for twins with two previous scars',
                'price' => 12000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 43,
                'service_name' => 'Cesarean - Twins 3rd Scar (165)',
                'description' => 'Cesarean section for twins with three previous scars',
                'price' => 13000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 44,
                'service_name' => 'Cesarean - Twins 4th Scar (1197)',
                'description' => 'Cesarean section for twins with four previous scars',
                'price' => 14000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 45,
                'service_name' => 'Cesarean - Twins 5th Scar (15000)',
                'description' => 'Cesarean section for twins with five previous scars',
                'price' => 15000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 46,
                'service_name' => 'Cystectomy (ovarian) - Laparatomy (167)',
                'description' => 'Ovarian cystectomy via laparotomy',
                'price' => 8000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 47,
                'service_name' => 'Cyst Removal - Bartholdi (168)',
                'description' => 'Bartholin cyst removal',
                'price' => 3000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 48,
                'service_name' => 'Ectopic Pregnancy (169)',
                'description' => 'Management of ectopic pregnancy',
                'price' => 8000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 49,
                'service_name' => 'Hysterectomy - Vaginal (170)',
                'description' => 'Vaginal hysterectomy procedure',
                'price' => 12000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 50,
                'service_name' => 'Hysterectomy Vaginal Anterior Colporaphy (171)',
                'description' => 'Vaginal hysterectomy with anterior colporrhaphy',
                'price' => 14000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 51,
                'service_name' => 'Hysterectomy - Vaginal Posterior Colporaphy (172)',
                'description' => 'Vaginal hysterectomy with posterior colporrhaphy',
                'price' => 14000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 52,
                'service_name' => 'Hysterectomy - Vaginal A/P Colporaphy (173)',
                'description' => 'Vaginal hysterectomy with anterior/posterior colporrhaphy',
                'price' => 15000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 53,
                'service_name' => 'Hysterectomy - Total Abdominal (Simple) (174)',
                'description' => 'Simple total abdominal hysterectomy',
                'price' => 10000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 54,
                'service_name' => 'Hysterectomy - Total Abdominal (Complicated) (175)',
                'description' => 'Complicated total abdominal hysterectomy',
                'price' => 14000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 55,
                'service_name' => 'Cervical Cerclage (178)',
                'description' => 'Cervical cerclage procedure',
                'price' => 5000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 56,
                'service_name' => 'Cervical Cerclage Removal (179)',
                'description' => 'Removal of cervical cerclage',
                'price' => 1000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 57,
                'service_name' => 'Abortion - MVA (180)',
                'description' => 'Manual vacuum aspiration abortion',
                'price' => 4000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 58,
                'service_name' => 'Abortion - Medication (181)',
                'description' => 'Medication abortion',
                'price' => 2000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 59,
                'service_name' => 'Abortion-E & C (182)',
                'description' => 'Evacuation and curettage abortion',
                'price' => 4000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 60,
                'service_name' => 'Abortion - D&C (1163)',
                'description' => 'Dilation and curettage abortion',
                'price' => 5000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 61,
                'service_name' => 'Removal of Placenta (MANUAL) (184)',
                'description' => 'Manual removal of placenta',
                'price' => 5000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 62,
                'service_name' => 'Removal of Breast Lump (185)',
                'description' => 'Excision of breast lump',
                'price' => 3000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 63,
                'service_name' => 'Removal of Stitch (186)',
                'description' => 'Suture removal',
                'price' => 300.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 64,
                'service_name' => 'Imperforate Hymen Dissection (187)',
                'description' => 'Surgical correction of imperforate hymen',
                'price' => 3000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 65,
                'service_name' => 'Perineal Repair - Primary (188)',
                'description' => 'Primary perineal repair',
                'price' => 5000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 66,
                'service_name' => 'Perineal Repair - Secondary (1195)',
                'description' => 'Secondary perineal repair',
                'price' => 7000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 67,
                'service_name' => 'Tevitory (1196)',
                'description' => 'Tevitory procedure',
                'price' => 7000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 68,
                'service_name' => 'TRANSVERSE VAGINAL SEPTUM RESECTION (5000)',
                'description' => 'Resection of transverse vaginal septum',
                'price' => 5000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 69,
                'service_name' => 'Circumcision for babies delivered elsewhere (2500)',
                'description' => 'Circumcision for infants born at other facilities',
                'price' => 2500.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 70,
                'service_name' => 'Adult Circumcision (2000)',
                'description' => 'Circumcision procedure for adults',
                'price' => 2000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 71,
                'service_name' => 'Circumcision for babies delivered here (2000)',
                'description' => 'Circumcision for infants born at this facility',
                'price' => 2000.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 72,
                'service_name' => 'Loop IUCD Insert (630)',
                'description' => 'Insertion of loop intrauterine contraceptive device',
                'price' => 630.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ],
            [
                'id' => 73,
                'service_name' => 'Loop Out (420)',
                'description' => 'Removal of loop intrauterine contraceptive device',
                'price' => 420.00,
                'billing_type' => 'one-time',
                'billing_interval_days' => null,
                'is_active' => true,
                'payment_timing' => 'postpaid',
                'created_at' => now(),
                'updated_at' => now(),
                'service_category_id' => 2,
            ]
        ]);
    }
}
