<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicalConditionSeeder extends Seeder
{
    public function run()
    {
        // Step 1: Insert Disease category with fixed ID = 1
        DB::table('condition_categories')->updateOrInsert(
            ['id' => 1],
            ['name' => 'Disease', 'type' => 'Diagnoses', 'description' => 'Category for diseases', 'created_at' => now(), 'updated_at' => now()]
        );

        $categoryId = 1; // Hardcoded ID

        // Step 2: List of [name, code] pairs
        $conditions = [
            ['Intestinal Infection', '1A02'],
            ['Tayphoid Fever', '1A08'],
            ['Typhus Fever', '1A07'],
            ['Bacterial Intestinal Infection', '1A0Z'],
            ['Food Poisoning', '1A1Z'],
            ['Giardiasis', '1A31'],
            ['Amoebiasis', '1A36'],
            ['Syphillis Unspecified', '1A6Z'],
            ['Gonococal Infection', '1A7Z'],
            ['Impetigo, unspecified', '1B72.Z'],
            ['Whooping cough', '1C12'],
            ['Rabies', '1C82'],
            ['Chlamydial Infection(Genitourinary Track Infection)', '1A80'],
            ['Trachoma, unspecified', '1C23.Z'],
            ['Cataract', '9B10'],
            ['Mumps', '1D80'],
            ['Acute Hepatitis-A', '1E50.0'],
            ['Acute Hepatitis-B', '1E50.1'],
            ['Acute Hepatitis-C', '1E50.2'],
            ['Acute Hepatitis-E', '1E50.3'],
            ['Common Warts', '1 E80'],
            ['Zoster', '1 E91'],
            ['Measles', '1F03'],
            ['Chronic viral hepatitis', '1E51'],
            ['Candidosis', '1F23'],
            ['Herpes Simplex Infection', '1F00'],
            ['Dermatophytosis of scalp', '1F28.0'],
            ['Dermato Phytosis Nail', '1F28.1'],
            ['Dermatophytosis of foot', '1F28.2'],
            ['Malaria Due to Plasmodium Falciparum', '1F40'],
            ['Malaria Due to Plasmodium Vivax', '1F41'],
            ['Ascites', 'ME04'],
            ['Ascaries', '1F62'],
            ['Dracunculiasis', '1F64'],
            ['Hookworm diseases', '1F68'],
            ['Septic shock', '1G41'],
            ['Leukaemia, unspecified', '2B33.4'],
            ['Stroke not known if ischaemic or haemorrhagic', '8B20'],
            ['Lipoma', '2E80.0'],
            ['Anemia', '3A00.Z'],
            ['Hypothyroidism', '5A00'],
            ['Allergic or hypersensitivity conditions of other specified type', '4A8Y'],
            ['Nontoxic goitre, unspecified', '5A01.Z'],
            ['Thyrotoxicosis', '5A02'],
            ['Type 1 Diabetes Mellitus', '5A10'],
            ['Type 2 Diabetes Mellitus', '5A11'],
            ['Hypoglycaemia without associated diabetes', '5A41'],
            ['Vitamin D deficiency rickets', '5B57.0'],
            ['Iodine deficiency', '5B5K.3'],
            ['Overweight', '5B80.0'],
            ['Obesity', '5B81'],
            ['Vitamin excesses', '5B90'],
            ['Mineral excesses', '5B91'],
            ['Dehydration', '5C70.0'],
            ['Hypovolaemia', '5C70.1'],
            ['Migraine', '8A80'],
            ['Tension Headache', '8A81'],
            ['Hydrocephalus', '8D64.Z'],
            ['Female pelvic inflammatory diseases', 'GA05'],
            ['Amenorrhoea', 'GA20.0'],
            ['Frequent menstrual bleeding', 'GA20.10'],
            ['Menopausal hot flush', 'GA30.4'],
            ['Female infertility', 'GA31'],
            ['Breast abscess', 'GB21.0'],
            ['Disorders of breast, unspecified', 'GB2Z'],
            ['Acute pyelonephritis', 'GB51'],
            ['Acute tubular necrosis', 'GB52'],
            ['Chronic kidney disease', 'GB61'],
            ['Cystitis', 'GC00'],
            ['Urinary tract infection, site not specified', 'GC08'],
            ['Male erectile dysfunction', 'HA01.1'],
            ['Spontaneous abortion', 'JA00.0'],
            ['Ectopic pregnancy, unspecified', 'JA01.Z'],
            ['Missed abortion', 'JA03'],
            ['Cleft lip', 'LA40'],
            ['Cleft palate', 'LA42'],
            ['Ectopic testis', 'LB52.0'],
            ['Eye Discharge', 'MC14'],
            ['Red Eye', 'MC15'],
            ['Epistaxsis', 'MD20'],
            ['Haemoptysis', 'MD22'],
            ['Schizophrenia', '6A20'],
            ['Delirium', '6D70'],
            ['Parkinson disease', '8A00.0'],
            ['Alzheimer disease', '8A20'],
            ['Febrile seizures', '8A63.0'],
            ['Status epilepticus', '8A66'],
            ['Allergic conjunctivitis', '9A60.02'],
            ['Corneal ulcer', '9A76'],
            ['Glaucoma', '9C61'],
            ['Acute otitis media', 'AB00'],
            ['Essential hypertension', 'BA00'],
            ['Angina pectoris', 'BA40'],
            ['Diabetic foot ulcer', 'BD54'],
            ['Lymphadenitis', 'BD90'],
            ['Acute sinusitis', 'CA01'],
            ['Acute ischaemic heart disease, unspecified', 'BA4Z'],
            ['Heart failure, unspecified', 'BD1Z'],
            ['Deep vein thrombosis', 'BD71'],
            ['Asthma', 'CA23'],
            ['Acute tonsillitis, unspecified', 'CA03.Z'],
            ['Pneumonia', 'CA40'],
            ['Acute bronchitis', 'CA42'],
            ['Dental caries', 'DA08.0'],
            ['Gingival diseases', 'DA0B'],
            ['Oesophagitis', 'DA24'],
            ['Gastritis', 'DA42'],
            ['Helicobacter pylori induced gastritis', 'DA42 1'],
            ['Duodenitis', 'DA51'],
            ['Gastric ulcer', 'DA60'],
            ['Duodenal ulcer', 'DA63'],
            ['Obstruction of small intestine', 'DA91'],
            ['Appendicitis', 'DB10'],
            ['Rectal prolapse', 'DB31.2'],
            ['Haemorrhoids', 'DB60'],
            ['Anal abscess', 'DB70.00'],
            ['Hepatic cirrhosis', 'DB93.1'],
            ['Chronic liver disease', 'DB99.0'],
            ['Cholelithiasis', 'DC11'],
            ['Acute pancreatitis', 'DC31'],
            ['Hernias, unspecified', 'DD5Z'],
            ['Infantile atopic eczema', 'EA80.0'],
            ['Psoriasis', 'EA90'],
            ['Vitiligo', 'ED63.0'],
            ['Allergic contact dermatitis', 'EK00'],
            ['Osteoarthritis of knee', 'FA01'],
            ['Rheumatoid arthritis', 'FA20'],
            ['Gout', 'FA25'],
            ['Dyspepsia', 'MD92'],
            ['Rash', 'ME66.6'],
            ['Oedema', 'MG29'],
            ['Shock', 'MG40'],
            ['Fracture of rib', 'NA82.3'],
            ['Burns, unspecified', 'NE2Z'],
            ['Vehicle driver injured in transport related event', 'XE42A'],
            ['Carbon monoxide poisoning [Harmful effects of substances]', 'NE60&NE60&XM1X11'],
            ['Other specified disorders of nerve root, plexus or peripheral nerves', '8C4Y'],
            ['Other specified diseases of the nervous system', '8E7Y'],
            ['Tuberculosis, unspecified', '1B1Z'],
            ['Other specified diseases of the respiratory system', 'CB40.Y'],
        ];


        DB::table('condition_categories')->updateOrInsert(
            ['id' => 2],
            ['name' => 'Treatment', 'type' => 'Treatment', 'description' => 'Category for treatment', 'created_at' => now(), 'updated_at' => now()]
        );

        $categoryId2 = 2; // Hardcoded ID

        // Step 2: List of [name, code] pairs
        $conditions2 = [
            ['Medication Prescription'],
            ['Surgery'],
            ['Vaccination'],
            ['Physiotherapy'],
            ['Chemotherapy'],
            ['Radiation Therapy'],
            ['Physical Therapy'],
            ['Occupational Therapy'],
            ['Speech Therapy'],
            ['Respiratory Therapy'],
            ['Cardiac Rehabilitation'],
            ['Nutritional Counseling'],
            ['Psychiatric Evaluation'],
            ['Pain Management Program'],
            ['Palliative Care'],
            ['Home Health Care'],
            ['Emergency Care'],
            ['Surgical Intervention'],
            ['Transfusion Medicine'],
            ['Dialysis Treatment'],
            ['Intravenous Therapy'],
            ['Blood Pressure Monitoring'],
            ['Blood Sugar Monitoring'],
            ['Cholesterol Management'],
            ['Anticoagulation Therapy'],
            ['Immunotherapy'],
            ['Hormone Replacement Therapy'],
            ['Physical Rehabilitation'],
            ['Speech Rehabilitation'],
            ['Occupational Rehabilitation'],
            ['Nutritional Rehabilitation'],
            ['Psychological Counseling'],
            ['Substance Abuse Treatment'],
            ['Pain Management Therapy'],
            ['Wound Care Management'],
            ['Infection Control Measures'],
            ['Patient Education'],
            ['Lifestyle Modification Program'],
            ['Smoking Cessation Program'],
            ['Weight Management Program'],
            ['Exercise Prescription'],
            ['Stress Management Program'],
            ['Sleep Apnea Treatment'],
            ['Chronic Pain Management'],
            ['Cardiac Monitoring'],
            ['Pulmonary Rehabilitation'],
            ['Diabetes Education'],
            ['Asthma Management Program'],
            ['Allergy Testing and Treatment'],
            ['Nutritional Supplements'],
            ['Physical Activity Counseling'],
            ['Medication Adherence Counseling'],
            ['Support Groups'],
            ['Telehealth Services'],
            ['Home Monitoring Devices'],
            ['Patient Navigation Services'],
            ['Care Coordination Services'],
            ['Chronic Disease Management'],
            ['Preventive Health Services'],
            ['Health Screenings'],
            ['Genetic Counseling'],
            ['Genetic Testing'],
            ['Pain Management Procedures'],
            ['Joint Injections'],
            ['Trigger Point Injections'],
            ['Epidural Steroid Injections'],
            ['Nerve Blocks'],
            ['Acupuncture'],
            ['Chiropractic Care'],
            ['Massage Therapy'],
            ['Biofeedback Therapy'],
            ['Transcutaneous Electrical Nerve Stimulation (TENS)'],
            ['Ultrasound Therapy'],
            ['Cryotherapy'],
            ['Heat Therapy'],
            ['Cold Therapy'],
            ['Hydrotherapy'],
            ['Therapeutic Exercise'],
            ['Range of Motion Exercises'],
            ['Strength Training'],
            ['Balance Training'],
            ['Coordination Training'],
            ['Endurance Training'],
            ['Functional Training'],
            ['Gait Training'],
            ['Posture Correction'],
            ['Ergonomic Assessment'],
            ['Assistive Devices'],
            ['Orthotics and Prosthetics'],
            ['Mobility Aids'],
            ['Home Modifications'],
            ['Adaptive Equipment'],
            ['Patient Advocacy'],
            ['Caregiver Support'],
            ['Community Resources Referral'],
            ['Transportation Services'],
            ['Meal Delivery Services'],
            ['Home Safety Assessment'],
            ['Medication Management Services'],
            ['Dialysis'],
            ['Counseling & Psychotherapy'],
            ['Wound Dressing'],
            ['IV Fluids'],
            ['Blood Transfusion'],
            ['Lifestyle Advice'],
            ['Nutritional Support'],
            ['Insulin Therapy'],
            ['Oxygen Therapy'],
            ['Antibiotic Therapy'],
            ['Antiviral Therapy'],
            ['Pain Management'],
            ['Admission & Observation'],
            ['Referral to Specialist'],
        ];


        DB::table('condition_categories')->updateOrInsert(
            ['id' => 3],
            ['name' => 'Medical Record', 'type' => 'Medical Record', 'description' => 'Category for Medical Record', 'created_at' => now(), 'updated_at' => now()]
        );

        $categoryId3 = 3; // Hardcoded ID

        // Step 2: List of [name, code] pairs
        $conditions3 = [
            ['Medication Prescription'],
            ['Surgery'],
            ['Vaccination'],
            ['Physiotherapy'],
            ['Chemotherapy'],
            ['Radiation Therapy'],
            ['Physical Therapy'],
            ['Occupational Therapy'],
            ['Speech Therapy'],
            ['Respiratory Therapy'],
            ['Cardiac Rehabilitation'],
            ['Nutritional Counseling'],
            ['Psychiatric Evaluation'],
            ['Pain Management Program'],
            ['Palliative Care'],
            ['Home Health Care'],
            ['Emergency Care'],
            ['Surgical Intervention'],
            ['Transfusion Medicine'],
            ['Dialysis Treatment'],
            ['Intravenous Therapy'],
            ['Blood Pressure Monitoring'],
            ['Blood Sugar Monitoring'],
            ['Cholesterol Management'],
            ['Anticoagulation Therapy'],
            ['Immunotherapy'],
            ['Hormone Replacement Therapy'],
            ['Physical Rehabilitation'],
            ['Speech Rehabilitation'],
            ['Occupational Rehabilitation'],
            ['Nutritional Rehabilitation'],
            ['Psychological Counseling'],
            ['Substance Abuse Treatment'],
            ['Pain Management Therapy'],
            ['Wound Care Management'],
            ['Infection Control Measures'],
            ['Patient Education'],
            ['Lifestyle Modification Program'],
            ['Smoking Cessation Program'],
            ['Weight Management Program'],
            ['Exercise Prescription'],
            ['Stress Management Program'],
            ['Sleep Apnea Treatment'],
            ['Chronic Pain Management'],
            ['Cardiac Monitoring'],
            ['Pulmonary Rehabilitation'],
            ['Diabetes Education'],
            ['Asthma Management Program'],
            ['Allergy Testing and Treatment'],
            ['Nutritional Supplements'],
            ['Physical Activity Counseling'],
            ['Medication Adherence Counseling'],
            ['Support Groups'],
            ['Telehealth Services'],
            ['Home Monitoring Devices'],
            ['Patient Navigation Services'],
            ['Care Coordination Services'],
            ['Chronic Disease Management'],
            ['Preventive Health Services'],
            ['Health Screenings'],
            ['Genetic Counseling'],
            ['Genetic Testing'],
            ['Fever'],
            ['Nausea'],
            ['Rash'],
            ['Fatigue'],
            ['Pain'],
            ['Swelling'],
            ['Itching'],
            ['Redness'],
            ['Burning sensation'],
            ['Tingling sensation'],
            ['Numbness'],
            ['Weakness'],
            ['Joint stiffness'],
            ['Muscle cramps'],
            ['Difficulty swallowing'],
            ['Difficulty breathing'],
            ['Chest tightness'],
            ['Cough'],
            ['Headache'],
            ['Abdominal pain'],
            ['Back pain'],
            ['Chest pain'],
            ['Shortness of breath'],
            ['Fatigue'],
            ['Vomiting'],
            ['Diarrhea'],
            ['Dizziness'],
            ['Sore throat'],
            ['Joint pain'],
            ['Skin rash'],
            ['Weight loss'],
            ['Blurred vision'],
            ['Urinary frequency'],
            ['Painful urination'],
            ['Nasal congestion'],
            ['Swelling'],
        ];


        // Step 3: Insert or update each condition
        foreach ($conditions as [$name, $code]) {
            DB::table('medical_conditions')->updateOrInsert(
                ['name' => trim($name)],
                [
                    'category_id' => $categoryId,
                    'code' => trim($code),
                    'description' => null,
                    'created_at' => now(),
                    'updated_at' => now()
                ]
            );
        }

        foreach ($conditions2 as [$name]) {
            DB::table('medical_conditions')->updateOrInsert(
                ['name' => trim($name)],
                [
                    'category_id' => $categoryId2,
                    'code' => null,
                    'description' => null,
                    'created_at' => now(),
                    'updated_at' => now()
                ]
            );
        }

        foreach ($conditions3 as [$name]) {
            DB::table('medical_conditions')->updateOrInsert(
                ['name' => trim($name)],
                [
                    'category_id' => $categoryId3,
                    'code' => null,
                    'description' => null,
                    'created_at' => now(),
                    'updated_at' => now()
                ]
            );
        }
    }
}
