<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnitSeeder extends Seeder
{
    public function run()
    {
        DB::table('units')->insert([
            [
                'id' => 1,
                'name' => 'Milligrams per Deciliter (mg/dL)',
                'code' => 'mg/dL',
                'description' => 'A unit of concentration commonly used for glucose, cholesterol, and other substances.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Micromoles per Liter (µmol/L)',
                'code' => 'µmol/L',
                'description' => 'A unit for measuring molar concentration in body fluids.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'International Units per Liter (IU/L)',
                'code' => 'IU/L',
                'description' => 'A unit of enzyme concentration used in clinical laboratory tests.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Units per Liter (U/L)',
                'code' => 'U/L',
                'description' => 'A unit for measuring enzyme activity in blood.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Millimoles per Liter (mmol/L)',
                'code' => 'mmol/L',
                'description' => 'A unit for measuring molar concentration in body fluids.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Grams per Deciliter (g/dL)',
                'code' => 'g/dL',
                'description' => 'A unit commonly used for measuring protein concentration.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Microsiemens per Centimeter (μS/cm)',
                'code' => 'μS/cm',
                'description' => 'A unit for measuring electrical conductivity of liquids.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Centimeters (cm)',
                'code' => 'cm',
                'description' => 'A unit of length used to measure physical dimensions.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Millimeters (mm)',
                'code' => 'mm',
                'description' => 'A smaller unit of length, typically used for small-scale measurements.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Kilograms (kg)',
                'code' => 'kg',
                'description' => 'A unit of mass commonly used for body weight or material weight.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Grams (g)',
                'code' => 'g',
                'description' => 'A unit of mass used for smaller weight measurements.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Micrograms (µg)',
                'code' => 'µg',
                'description' => 'A unit of mass equal to one millionth of a gram.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'Millimoles (mmol)',
                'code' => 'mmol',
                'description' => 'A unit for the amount of a substance based on molar quantity.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'Pico moles (pmol)',
                'code' => 'pmol',
                'description' => 'A unit used for very small amounts of substance, equal to 10^-12 moles.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'Milliliter (mL)',
                'code' => 'mL',
                'description' => 'A unit of volume commonly used in liquid measurements.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'Liters (L)',
                'code' => 'L',
                'description' => 'A standard unit for measuring the volume of liquids.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'Millimeters of Mercury (mmHg)',
                'code' => 'mmHg',
                'description' => 'A unit of pressure, often used for blood pressure measurements.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'Seconds (s)',
                'code' => 's',
                'description' => 'A unit of time measurement.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'Minutes (min)',
                'code' => 'min',
                'description' => 'A unit of time, equal to 60 seconds.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'Hours (h)',
                'code' => 'h',
                'description' => 'A unit of time, equal to 60 minutes.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name' => 'Square Millimeters (mm²)',
                'code' => 'mm²',
                'description' => 'A unit of area, used for measuring small surfaces.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'name' => 'Square Centimeters (cm²)',
                'code' => 'cm²',
                'description' => 'A unit of area, commonly used in surface area measurements.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'name' => 'Cubic Millimeters (mm³)',
                'code' => 'mm³',
                'description' => 'A unit of volume for small-scale measurements.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'name' => 'Cubic Centimeters (cm³)',
                'code' => 'cm³',
                'description' => 'A unit of volume, commonly used for liquid volumes.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'name' => 'Microliters (µL)',
                'code' => 'µL',
                'description' => 'A unit of volume used in micro scale liquid measurements.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'Nanograms per Milliliter (ng/mL)',
                'code' => 'ng/mL',
                'description' => 'A unit of concentration used for measuring very small amounts.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'name' => 'Picograms per Milliliter (pg/mL)',
                'code' => 'pg/mL',
                'description' => 'A unit of concentration, one trillionth of a gram per milliliter.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'name' => 'Pico moles per Liter (pmol/L)',
                'code' => 'pmol/L',
                'description' => 'A unit of concentration equal to one trillionth of a mole per liter.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'name' => 'Micromolar (µM)',
                'code' => 'µM',
                'description' => 'A unit of molar concentration equal to one millionth of a mole per liter.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'name' => 'Nanomolar (nM)',
                'code' => 'nM',
                'description' => 'A unit of molar concentration equal to one billionth of a mole per liter.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'name' => 'Picomolar (pM)',
                'code' => 'pM',
                'description' => 'A unit of molar concentration equal to one trillionth of a mole per liter.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'name' => 'Hematocrit Percentage (Hct)',
                'code' => 'Hct',
                'description' => 'The percentage of blood volume occupied by red blood cells.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'name' => 'Blood Pressure (mmHg)',
                'code' => 'mmHg',
                'description' => 'A unit for measuring blood pressure, indicating millimeters of mercury.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'name' => 'Osmolality (mOsm/kg)',
                'code' => 'mOsm/kg',
                'description' => 'A unit of measurement for osmolality (moles of solute per kilogram of solvent).',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'name' => 'Centrifugal Force (g)',
                'code' => 'g',
                'description' => 'A measure of the acceleration experienced by an object in a centrifuge.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'name' => 'Relative Density (g/cm³)',
                'code' => 'g/cm³',
                'description' => 'The ratio of the density of a substance to the density of water.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'name' => 'Millivolts (mV)',
                'code' => 'mV',
                'description' => 'A unit of electric potential, often used in electrochemical measurements.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'name' => 'Coulombs (C)',
                'code' => 'C',
                'description' => 'A unit of electric charge.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'name' => 'Nanoseconds (ns)',
                'code' => 'ns',
                'description' => 'A unit of time equal to one billionth of a second.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'name' => 'Microseconds (µs)',
                'code' => 'µs',
                'description' => 'A unit of time equal to one millionth of a second.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'name' => 'Milliseconds (ms)',
                'code' => 'ms',
                'description' => 'A unit of time equal to one thousandth of a second.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'name' => 'Microvolts (µV)',
                'code' => 'µV',
                'description' => 'A unit of electric potential equal to one millionth of a volt.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'name' => 'Kiloelectrons Volts (keV)',
                'code' => 'keV',
                'description' => 'A unit of energy used in atomic physics.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'name' => 'Joules (J)',
                'code' => 'J',
                'description' => 'A unit of energy, work, or amount of heat.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'name' => 'Volts (V)',
                'code' => 'V',
                'description' => 'A unit of electric potential, commonly used to measure voltage.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'name' => 'Ampere (A)',
                'code' => 'A',
                'description' => 'The unit of electric current.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'name' => 'Microamperes (µA)',
                'code' => 'µA',
                'description' => 'A unit of electric current equal to one millionth of an ampere.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'name' => 'KiloJoules (kJ)',
                'code' => 'kJ',
                'description' => 'A unit of energy, equal to 1,000 joules.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'name' => 'Kilocalories (kcal)',
                'code' => 'kcal',
                'description' => 'A unit of energy used in food and nutrition.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'name' => 'Microsiemens per Centimeter (µS/cm)',
                'code' => 'µS/cm',
                'description' => 'A unit of electrical conductivity.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'name' => 'Micrograms per Liter (µg/L)',
                'code' => 'µg/L',
                'description' => 'A unit of concentration representing one millionth of a gram per liter.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'name' => 'Pieces (pcs)',
                'code' => 'pcs',
                'description' => 'Individual tablets or capsules.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'name' => 'Milliequivalents per Liter (mEq/L)',
                'code' => 'mEq/L',
                'description' => 'A unit of concentration for ions in a solution.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'name' => 'Nano Grams per Deciliter (ng/dL)',
                'code' => 'ng/dL',
                'description' => 'A unit of concentration in which nanograms of substance are measured per deciliter of solution.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'name' => 'Moles per Liter (mol/L)',
                'code' => 'mol/L',
                'description' => 'A unit of molarity, representing the number of moles of solute per liter of solution.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'name' => 'Parts per Million (ppm)',
                'code' => 'ppm',
                'description' => 'A unit of concentration commonly used to express small amounts of contaminants.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'name' => 'Parts per Billion (ppb)',
                'code' => 'ppb',
                'description' => 'A unit of concentration used for extremely low levels of contaminants.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'name' => 'Percent (%)',
                'code' => '%',
                'description' => 'A unit of proportion or percentage, representing parts per hundred.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'name' => 'MiliMoles per Liter (mM)',
                'code' => 'mM',
                'description' => 'A unit of molar concentration representing one thousandth of a mole per liter.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'name' => 'Picometers (pm)',
                'code' => 'pm',
                'description' => 'A unit of length equal to one trillionth of a meter.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'name' => 'Millimeters (mm)',
                'code' => 'mm',
                'description' => 'A unit of length equal to one thousandth of a meter.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'name' => 'Centimeters (cm)',
                'code' => 'cm',
                'description' => 'A unit of length equal to one hundredth of a meter.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'name' => 'Meters (m)',
                'code' => 'm',
                'description' => 'The standard unit of length in the metric system.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'name' => 'Kilometers (km)',
                'code' => 'km',
                'description' => 'A unit of length equal to one thousand meters.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'name' => 'Grams (g)',
                'code' => 'g',
                'description' => 'A unit of mass in the metric system.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'name' => 'Milligrams (mg)',
                'code' => 'mg',
                'description' => 'A unit of mass equal to one thousandth of a gram.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'name' => 'Micrograms (µg)',
                'code' => 'µg',
                'description' => 'A unit of mass equal to one millionth of a gram.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'name' => 'Nanograms (ng)',
                'code' => 'ng',
                'description' => 'A unit of mass equal to one billionth of a gram.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 69,
                'name' => 'Potential of Hydrogen (pH)',
                'code' => 'pH',
                'description' => 'A measure of the hydrogen ion concentration, indicating the acidity or alkalinity of a solution.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'name' => 'White Blood Cells Count (WBC)',
                'code' => 'WBC',
                'description' => 'A count of the number of white blood cells in a sample, used to assess immune function and detect infections.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'name' => 'Beats Per Minute',
                'code' => 'bpm',
                'description' => 'Unit for measuring heart rate, representing the number of heartbeats per minute.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'name' => 'Celsius',
                'code' => '°C',
                'description' => 'Unit for measuring temperature, representing degrees Celsius.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 73,
                'name' => 'Breaths Per Minute',
                'code' => 'bpm',
                'description' => 'Unit for measuring respiratory rate, representing the number of breaths per minute.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'name' => 'Nano Moles per Liter (nmol/L)',
                'code' => 'nmol/L',
                'description' => 'A unit of molarity, representing the number of nanomoles of solute per liter of solution.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'name' => 'Milli-international units per Milliliter (mIU/mL)',
                'code' => 'mIU/mL',
                'description' => 'A unit of concentration, representing the number of milli-international units of substance per milliliter of solution.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 76,
                'name' => 'Milligrams per Liter (mg/L)',
                'code' => 'mg/L',
                'description' => 'A unit of concentration commonly used for glucose, cholesterol, and other substances.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'name' => 'Thousands per Microliter (10^3/µL)',
                'code' => '10^3/µL',
                'description' => 'Used to express white blood cell (WBC), platelet, and other counts in thousands per microliter.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 78,
                'name' => 'Millions per Microliter (10^6/µL)',
                'code' => '10^6/µL',
                'description' => 'Used to express red blood cell (RBC) counts in millions per microliter.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 79,
                'name' => 'Billions per Microliter (10^9/µL)',
                'code' => '10^9/µL',
                'description' => 'Used to express white blood cell (WBC) counts in billions per microliter.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 80,
                'name' => 'Units per Microliter (U/µL)',
                'code' => 'U/µL',
                'description' => 'A unit of concentration for enzymes or other substances in microliters.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'name' => 'Femtoliter (fL)',
                'code' => 'fL',
                'description' => 'A unit of volume equal to one quadrillionth of a liter.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 82,
                'name' => 'Picograms (pg)',
                'code' => 'pg',
                'description' => 'A unit of concentration, one trillionth of a gram.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 83,
                'name' => 'Millimeters per Hour (mm/hr)',
                'code' => 'mm/hr',
                'description' => 'It is a unit of measurement, specifically used to express the rate at which red blood cells settle in a blood sample during the Erythrocyte Sedimentation Rate (ESR) test.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
